import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.min.js';
import {createBonePhysics} from '../bone-physics.mjs';

const physics=createBonePhysics({ground:0,arena:20,pods:[{x:10,z:10}]});
const entity=(x=0,z=0)=>({x,y:0,z,slaughterYaw:0,g:new THREE.Group()});
const step=frames=>{for(let i=0;i<frames;i++)physics.step(1/60);};
const lower=entity();
physics.add(lower,1);
assert.equal(physics.status(lower).shapes,2);
assert.ok(physics.status(lower).mass>0);
step(360);
assert.ok(lower.boneBounds.minY>-.03&&lower.boneBounds.minY<.08);
assert.ok(physics.status(lower).sleeping);
const upper=entity();
physics.add(upper,1);
assert.ok(upper.boneBounds.minY>=lower.boneBounds.maxY-.02,'new body spawns above the pile');
step(360);
assert.ok(upper.boneBounds.minY>lower.boneBounds.minY+.5,'upper bones stay above the ground layer');
assert.ok(upper.boneBounds.minY>=lower.boneBounds.maxY-.06,'bone bodies support each other');
assert.ok(physics.supportHeight(0,0)>.9);
const frozen=upper.g.position.clone();
physics.step(0);
assert.deepEqual(upper.g.position.toArray(),frozen.toArray());
const walker={x:0,y:.1,z:0,vx:0,vz:-2};
physics.constrain(walker);
assert.ok(Math.hypot(walker.x,walker.z)>.3,'player cannot walk through the pile');
const flyer={x:0,y:5,z:0};
physics.constrain(flyer);
assert.equal(flyer.x,0);assert.equal(flyer.z,0);
assert.ok(physics.applyImpulse(upper,{x:1,y:2,z:0}));
assert.ok(!physics.status(upper).sleeping);
assert.equal(physics.applyImpulse(upper,{x:NaN,y:0,z:0}),false);
assert.ok(physics.remove(upper));assert.equal(physics.status(upper),null);
physics.teleport(lower,{x:10,y:7,z:10});
step(360);
assert.ok(lower.boneBounds.minY>=5.35,'capsule collider supports falling bones');
physics.dispose();
assert.equal(physics.status(lower),null);
console.log('ok   bone rigid bodies: gravity, stacking, character bounds, sleeping and lifecycle');
